version: "3.8"
services:
  backend:
    build:
      context: ./zet-flow-spring
      dockerfile: Dockerfile
    image: zet-flow-spring:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./zet-flow-angular
      dockerfile: Dockerfile
    image: zet-flow-angular:latest
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=http://backend:8080
      - API_WS_URL=ws://backend:8080/ws
    depends_on:
      backend:
        condition: service_healthy

